version: "3"
   
services:
  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'wpopdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db:/var/lib/mysql
  django:
    build: .
    command: bash -c "python3 tvfinder/manage.py makemigrations && 
                      python3 tvfinder/manage.py migrate && 
                      python3 tvfinder/fill_database.py &&
                      python3 tvfinder/manage.py runserver 0.0.0.0:8000"
    restart: on-failure
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on: #links:
      - db
